pokemon/urls.py
from django.urls import path
from . import views

app_name = "pokemon"

urlpatterns = [
    path('', views.home, name='home'),
    path('load-pokedex/', views.load_pokedex, name='load-pokedex'),
    path('my-teams/', views.my_teams, name='my-teams'),
    path('create-team/', views.create_team, name='create-team'),
    path('generate-team/', views.generate_team, name='generate-team'),
    path('reshuffle/<int:data_id>', views.reshuffle, name='reshuffle'),
    path('save-team/', views.save_team, name='save-team'),
]

pokemon_team_builder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokemon.urls')),
]

pokemon/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# pokemon team model
class Team(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    team_name = models.CharField(max_length=255, blank=False)
    description = models.TextField(max_length=255, blank=True)
    slot_0 = models.IntegerField(blank=False, default=0)
    slot_1 = models.IntegerField(blank=False, default=0)
    slot_2 = models.IntegerField(blank=False, default=0)
    slot_3 = models.IntegerField(blank=False, default=0)
    slot_4 = models.IntegerField(blank=False, default=0)
    slot_5 = models.IntegerField(blank=False, default=25)

    def __str__(self):
        return self.team_name

pokemon/views.py
from django.shortcuts import render, redirect
from .randomize import randomize, single_randomize
from .models import Team
import requests


# this is the default home page
def home(request):
    return render(request, 'pokemon/home.html', {})


def load_pokedex(request):
    # request.session.flush()

     # url = "https://pokeapi.co/api/v2/pokemon/mewtwo" #this is for single pokemon API calls

    #this is for batch pokemon API calls
    batch_url = "https://pokeapi.co/api/v2/pokemon?limit=10" 
    res = requests.get(batch_url)

    if res.status_code != 200:
        print(res.text)
    else:
        # GET batch pokemon data to API
        data = res.json()

        # make json object to list
        list_urls = [i for i in data['results']]        #this contains the urls of each pokemon from batch GET
        final_data = []
        animated_gifs = []

        # iterate over each urls
        for url in list_urls:
            response = requests.get(url['url'])

            if response.status_code != 200:
                print(response.text)
            else:
                # GET specific data of a pokemon
                new_data = response.json()

                #this is to extract the animated GIFs
                animated_gif = new_data['sprites']['versions']['generation-v']['black-white']['animated']['front_default']              

                #append the pokemon data and GIFs to array
                final_data.append(new_data)    
                animated_gifs.append(animated_gif)      
       
        # pass data to sessions
        request.session['pokedata'] = {
            'pokemondata': final_data
        }

        request.session['animated'] = {
            'gif': animated_gifs
        }

        # context = {
        #     'pokedata': final_data,
        #     'gifdata': animated_gifs
        # }
        return redirect('pokemon:home')


def my_teams(request):
    # query the database here
    all_team_data = Team.objects.all().order_by('id')
    context = {
        'team_data': all_team_data
    }
    # get all the existing teams of a given user
    return render(request, 'pokemon/my_teams.html', context)


def create_team(request):
    
    return render(request, 'pokemon/create_team.html', {})


# this is for generating a line up for team 
def generate_team(request):
    # flush the sessions
    # request.session.flush()

    url = "https://pokeapi.co/api/v2/pokemon/"

    list_result = randomize(5)
    list_result.append(25)
    print("these are the results: ", str(list_result))
    team_data = []
    team_gifs = []

    # get the data of number from the PokeAPI   
    # iterate over each urls
    for number in list_result:
        response = requests.get(url + str(number))
        

        if response.status_code != 200:
            print(response.text)
        else:
            # GET specific data of a pokemon
            new_data = response.json()

            #this is to extract the animated GIFs
            animated_gif = new_data['sprites']['versions']['generation-v']['black-white']['animated']['front_default']              

            #append the pokemon data and GIFs to array
            team_data.append(new_data)    
            team_gifs.append(animated_gif)

    # print(team_data)             
    # pass data to sessions
    request.session['listresult'] = {
        'list_result': list_result
    }

    request.session['teamdata'] = {
        'lineup': team_data
    }

    request.session['teamgif'] = {
        'gif': team_gifs
    }


    return redirect('pokemon:create-team')



# for reshuffling a specific pokemon in team creation
def reshuffle(request, data_id):

    url = "https://pokeapi.co/api/v2/pokemon/"

    original = request.session['listresult']['list_result']
    # fetch the new team lineup
    new_lineup = single_randomize(original, data_id)

    team_data = []
    team_gifs = []

    # generate new data
    for number in new_lineup:
        response = requests.get(url + str(number))
    

        if response.status_code != 200:
            print(response.text)
        else:
            # GET specific data of a pokemon
            new_data = response.json()

            #this is to extract the animated GIFs
            animated_gif = new_data['sprites']['versions']['generation-v']['black-white']['animated']['front_default']              

            #append the pokemon data and GIFs to array
            team_data.append(new_data)    
            team_gifs.append(animated_gif)

    print(new_lineup)
    # save data to session
    request.session['listresult'] = {
        'list_result': new_lineup
    }

    request.session['teamdata'] = {
        'lineup': team_data
    }

    request.session['teamgif'] = {
        'gif': team_gifs
    }
    
    return redirect('pokemon:create-team')


# function for saving a generated team to database
def save_team(request):
    # simple validation
    if request.method == 'POST':
        # get data from the form
        team_name = request.POST['team_name']
        description = request.POST['team_desc']
        slot_0 = request.POST['slot_0']
        slot_1 = request.POST['slot_1']
        slot_2 = request.POST['slot_2']
        slot_3 = request.POST['slot_3']
        slot_4 = request.POST['slot_4']
        slot_5 = request.POST['slot_5']

        # create a new save item
        new_team = Team(
            team_name = team_name,
            description = description,
            slot_0 = slot_0,
            slot_1 = slot_1,
            slot_2 = slot_2,
            slot_3 = slot_3,
            slot_4 = slot_4,
            slot_5 = slot_5
        )

        # save to database
        new_team.save()

        # delete session keys
        del request.session['teamdata']
        del request.session['teamgif']

    else:
        return redirect('pokemon:create-team')

    return redirect('pokemon:my-teams')

pokemon/templates/pokemon/create_team.html
{% extends 'base.html' %}
{% load zip %}

{% block title %}
    <title>Create a Team</title>
{% endblock title %}

{% block content %}
    <div class="create-team container p-4">
        
        <div class="team-body">
           
            <!-- insert here the slots and the cards you acquired from randomization -->
            <div class="your-team-cards py-3">
                <h4 class="text-center">Here are your Pokemons</h4>
                <hr class="mx-auto" width="70">
                <div class="d-grid container">
                    <a href="{% url 'pokemon:generate-team' %}" class="btn btn-dark">Generate Pokemon Team</a>
                </div>
                <div class="team-cards">
                    <!-- insert here the team_slot_card -->
                    <div class="row p-4 g-2">
                        {% if request.session.teamdata.lineup %}
                            {% for data, gif in request.session.teamdata.lineup|zip:request.session.teamgif.gif %}
                            <div class="col-12 col-lg-6">
                                {% include 'pokemon/includes/team_pokemon_card.html' %}
                            </div>
                            {% endfor %}
                        {% else %}
                            
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="header text-center">
                <!-- <h3>Generate Team</h3> -->
                <!-- <p>Have your pokemons generated first</p> -->
            </div>
            <div class="team-form">
                <form action="{% url 'pokemon:save-team' %}" method="POST" class="px-4">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="team_name" class="form-label">Team name</label>
                      <input type="text" class="form-control" id="team_name" name="team_name" required>
                    </div>
                    <div class="mb-3">
                      <label for="team_desc" class="form-label">Description</label>
                      <textarea type="text" class="form-control" id="team_desc" name="team_desc" required></textarea>
                    </div>
                    <!-- hidden values -->
                    {% for number in request.session.listresult.list_result %}
                         <input type="hidden" name="slot_{{ forloop.counter0 }}" value="{{ number }}">
                    {% endfor %}
                    <button type="submit" class="btn btn-dark px-4">Save your Team</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

pokemon/templates/pokemon/home.html
{% extends 'base.html' %} {% block title %}
<title>Pokemon Team Builder | Home</title>
{% endblock title %} {% block content %}
<div class="hero-section container text-center py-4">
  <div class="hero-img">
    <img
      src="https://upload.wikimedia.org/wikipedia/commons/9/98/International_Pok%C3%A9mon_logo.svg"
      alt="pokemon-logo"
      width="300"
    />
  </div>
  <div class="hero-body container py-4 d-grid gap-2">
    <a href="{% url 'pokemon:my-teams' %}" class="btn btn-dark">Build your team</a>

    <a href="{% url 'pokemon:load-pokedex' %}" class="btn btn-outline-dark"
      >Load PokeDex</a
    >
  </div>
</div>
<div class="main-content container overflow-hidden">
  <!-- show here the pokemon cards from the PokeAPI -->
  <div class="cardheader text-center">
    <h3>PokeDex</h3>
    <hr class="mx-auto" width="50" />
  </div>

  <!-- insert here the cards -->
  <div class="row p-4 g-2">
    {% include 'pokemon/includes/main_cards_display.html' %}
  </div>
</div>
{% endblock content %}

pokemon/templates/pokemon/includes/download-icon.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M14 10h5l-7 8-7-8h5v-10h4v10zm4.213-8.246l-1.213 1.599c2.984 1.732 5 4.955 5 8.647 0 5.514-4.486 10-10 10s-10-4.486-10-10c0-3.692 2.016-6.915 5-8.647l-1.213-1.599c-3.465 2.103-5.787 5.897-5.787 10.246 0 6.627 5.373 12 12 12s12-5.373 12-12c0-4.349-2.322-8.143-5.787-10.246z"/></svg>

pokemon/templates/pokemon/includes/empty_state.html
<div class="empty-state text-center">
    <div class="image-holder">
        <img src="https://i.gifer.com/origin/28/2860d2d8c3a1e402e0fc8913cd92cd7a_w200.gif" alt="animated-gif">
    </div>
    <div>
        <p>Ooppss, looks like you have <br> to load the PokeDex first</p>
    </div>
</div>

pokemon/templates/pokemon/includes/empty_state_team.html
<div class="empty-state text-center">
    <div class="image-holder">
        <img src="https://i.gifer.com/origin/28/2860d2d8c3a1e402e0fc8913cd92cd7a_w200.gif" alt="animated-gif">
    </div>
    <div>
        <p>Ooppss, looks like you don't have any teams yet. <br>Try adding one</p>
    </div>
</div>

pokemon/templates/pokemon/includes/main_cards_display.html
{% load zip %}

{% if request.session.pokedata.pokemondata %}
    {% for data, gif in request.session.pokedata.pokemondata|zip:request.session.animated.gif %}

        <div class="col-6 col-md-4 col-lg-3 text-center">
            {% include 'pokemon/includes/pokemon_card.html' %}
        </div>
        
    {% endfor %}
{% else %}
    {% include 'pokemon/includes/empty_state.html' %}
{% endif %}

pokemon/templates/pokemon/includes/pokemon_card.html
<!-- INSERT CONTEXT DATA HERE -->
<div class="card shadow-sm border-warning h-100">
    <div class="card-body">
        <div>
            <!-- <img src="{{ pokedata.sprites.front_default }}" alt="{{ pokedata.name }}-image"> -->
            {% if gif %}
                <img src="{{ gif }}" alt="{{ data.name }}-image">
            {% else %}
                <img src="{{ data.sprites.front_default }}" alt="{{ data.name }}-image">
            {% endif %}
        </div>
        <div class="title">
            <h2>{{ data.name }}</h2>
            <hr class="my-1 mx-auto" width="80">
        </div>
        <div class="body">
            <p class="fs-6">
               <em>height: </em>{{ data.height }} <br/>
                <em>weight: </em>{{ data.weight }} <br/>
                <em>type:</em>
                {% for type in data.types %}
                {{ type.type.name }} |
                {% endfor %}
            </p>
        </div>
    </div>
</div>

pokemon/templates/pokemon/includes/team_card.html
<div class="card shadow-sm h-100">
    <div class="card-body">
        <h3>{{ data.team_name }}</h3>
        <p>{{ data.description|truncatechars:35 }}</p>
    </div>
</div>

pokemon/templates/pokemon/includes/team_cards.html
    <a href="#" class="col-12 col-lg-6 btn btn-dark shadow-sm h-100 text-start py-2">
       
            {% comment %} {% include 'pokemon/includes/team_card.html' %} {% endcomment %}  
            <div class="card-body">
                <h3>{{ data.team_name }}</h3>
                <p>{{ data.description|truncatechars:35 }}</p>
            </div>
    </a>

    

    
    



 

pokemon/templates/pokemon/includes/team_pokemon_card.html
<div class="card h-100 shadow-sm border-warning">
    <div class="card-body row align-items-center">
        <div class="pokemon-image col-4 justify-self-center ps-4">
                {% if gif %}
                    <img src="{{ gif }}" alt="{{ data.name }}-image">
                {% else %} 
                    <img src="{{ data.sprites.front_default }}" alt="{{ data.name }}-image">
                {% endif %}
        </div>
        <div class="pokemon-stats ps-4 col-8">
            <h5>{{ data.name }}</h5>
            <p>
                <em>type:</em>
                {% for type in data.types %}
                {{ type.type.name }} |
                {% endfor %}
            </p>
            <form action="{% url 'pokemon:reshuffle' data.id %}">
                {% csrf_token %}
                <button id="reshuffle" type="submit" class="btn btn-sm btn-outline-dark">reshuffle</button>
            </form>
        </div>
    </div>
</div>

pokemon/templates/pokemon/my_teams.html
{% extends 'base.html' %}

{% block title %}
    <title>My Teams</title>
{% endblock title %}

{% block content %}
    <div class="my-teams container p-4">
        <div class="header text-center">
            <h2>YOUR TEAMS</h2>
            <p>Start building your dream team</p>
            <a href="{% url 'pokemon:create-team' %}" class="btn btn-dark btn-md">Create a team</a>
            <hr class="mx-auto" width="100">
        </div>
        <div class="main-content">
            {% if team_data %}
                <div class="row py-4 g-2">
                {% for data in team_data %}
                    {% include 'pokemon/includes/team_cards.html' %}
                {% endfor %}
                </div>
            {% else %}
                {% include 'pokemon/includes/empty_state_team.html' %}
            {% endif %} 
        </div>
        
    </div>
    
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock title %}

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <!-- GOOGLE FONTS -->
    <!-- <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600;700&display=swap" rel="stylesheet"> -->
</head> 
<body>
    <!-- here goes the navbar -->
    {% include 'includes/navbar_component.html' %}

    <!-- here goes the main content -->
    <div>
        {% block content %}{% endblock content %}
    </div>

    <!-- here goes the footer -->
    {% include 'includes/footer_component.html' %}
    
</body>

    <!-- BOOTSTRAP JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
</html>

templates/includes/footer_component.html
<footer>
    <div class="bg-dark text-light py-3 container-fluid">
        <p class="fs-6">Developed with ❤️ by <br>Mike Jerrson Galindez</p>   
    </div>
</footer>

templates/includes/navbar_component.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid d-flex">
      <div>
        <a class="navbar-brand" href="{% url 'pokemon:home' %}">
            <img src="https://upload.wikimedia.org/wikipedia/commons/9/98/International_Pok%C3%A9mon_logo.svg" class="img-fluid" width="150" alt="pokemon-logo">
          </a>
      </div>  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'pokemon:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pokemon:my-teams' %}">My Team</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>